name: Build and Release LabAI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/req/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req/requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run: |
          pyinstaller spec.spec

      - name: Move artifact to root
        run: |
          mkdir -p ./LabAI-ubuntu/_internal
          mv ./dist/* ./LabAI-ubuntu/_internal/

      - name: Add media folder to _internal
        run: cp -r ./media ./LabAI-ubuntu/_internal/

      - name: Compress artifact
        run: zip -r LabAI-ubuntu.zip ./LabAI-ubuntu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LabAI-ubuntu
          path: ./LabAI-ubuntu.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/req/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req/requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run: |
          pyinstaller spec.spec

      - name: Move artifact to root
        run: |
          mkdir -p ./LabAI-windows/_internal
          mv ./dist/* ./LabAI-windows/_internal/

      - name: Add media folder to _internal
        run: cp -r ./media ./LabAI-windows/_internal/

      - name: Compress artifact
        run: powershell Compress-Archive -Path ./LabAI-windows/* -DestinationPath ./LabAI-windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LabAI-windows
          path: ./LabAI-windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gettext
        run: brew install gettext
        shell: bash

      - name: Add gettext to PATH
        run: echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/req/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req/requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run: |
          pyinstaller spec.spec

      - name: Move artifact to root
        run: |
          mkdir -p ./LabAI-macos/_internal
          mv ./dist/* ./LabAI-macos/_internal/

      - name: Add media folder to _internal
        run: cp -r ./media ./LabAI-macos/_internal/

      - name: Compress artifact
        run: zip -r LabAI-macos.zip ./LabAI-macos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LabAI-macos
          path: ./LabAI-macos.zip
