name: Build and Release LabAI

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-ubuntu
        path: ./dist

  build-and-release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-windows
        path: ./dist

  build-and-release-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install gettext
      run: brew install gettext
      shell: bash

    - name: Add gettext to PATH
      run: echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-macos
        path: ./dist

  create-release:
    needs: [build-and-release-ubuntu, build-and-release-windows, build-and-release-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Artifact - Ubuntu
      uses: actions/download-artifact@v2
      with:
        name: LabAI-ubuntu
        path: artifacts/ubuntu

    - name: Download Artifact - Windows
      uses: actions/download-artifact@v2
      with:
        name: LabAI-windows
        path: artifacts/windows

    - name: Download Artifact - macOS
      uses: actions/download-artifact@v2
      with:
        name: LabAI-macos
        path: artifacts/macos

    - name: List Downloaded Files - Ubuntu
      run: ls -l artifacts/ubuntu

    - name: List Downloaded Files - Windows
      run: ls -l artifacts/windows

    - name: List Downloaded Files - macOS
      run: ls -l artifacts/macos

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Releases"
        release_name: "Releases"
        files: |
          artifacts/ubuntu/LabAI-ubuntu
          artifacts/windows/LabAI-windows
          artifacts/macos/LabAI-macos
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
