name: Build and Release LabAI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-ubuntu
        path: ./dist/*

  build-and-release-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-windows
        path: ./dist/*

  build-and-release-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install gettext
      run: brew install gettext
      shell: bash

    - name: Add gettext to PATH
      run: echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create Executable
      run: |
        pyinstaller spec.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LabAI-macos
        path: ./dist/*

  create-release:
    needs: [build-and-release-ubuntu, build-and-release-windows, build-and-release-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create directories for artifacts
      run: |
        mkdir -p artifacts/ubuntu
        mkdir -p artifacts/windows
        mkdir -p artifacts/macos

    - name: Download Artifact - Ubuntu
      uses: actions/download-artifact@v2
      with:
        name: LabAI-ubuntu
        path: artifacts/ubuntu

    - name: Download Artifact - Windows
      uses: actions/download-artifact@v2
      with:
        name: LabAI-windows
        path: artifacts/windows

    - name: Download Artifact - macOS
      uses: actions/download-artifact@v2
      with:
        name: LabAI-macos
        path: artifacts/macos

    - name: List Downloaded Files - Ubuntu
      run: ls -l artifacts/ubuntu

    - name: List Downloaded Files - Windows
      run: ls -l artifacts/windows

    - name: List Downloaded Files - macOS
      run: ls -l artifacts/macos

    - name: Get current timestamp
      id: ts
      run: echo "RELEASE_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v1.0.0-${{ env.RELEASE_TIME }}"
        release_name: "LabAI Release - ${{ env.RELEASE_TIME }}"
        body: "Release notes for LabAI"
        draft: false
        prerelease: false

    - name: Upload Release Asset - Ubuntu
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/ubuntu/*
        asset_name: LabAI-ubuntu-${{ env.RELEASE_TIME }}
        asset_content_type: application/zip

    - name: Upload Release Asset - Windows
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/windows/*
        asset_name: LabAI-windows-${{ env.RELEASE_TIME }}
        asset_content_type: application/zip

    - name: Upload Release Asset - macOS
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/macos/*
        asset_name: LabAI-macos-${{ env.RELEASE_TIME }}
        asset_content_type: application/zip
